FROM python:3.12.10-slim

WORKDIR /app

# Установка системных зависимостей, включая postgresql-client
RUN apt-get update && apt-get install -y \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

COPY ../requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --upgrade pip

COPY . .

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]