services:
  db:
    image: postgres:16
    container_name: calendar_db
    hostname: db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}   # ← обязательный пароль
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  django:
    build:
      context: ./django-admin-panel
      dockerfile: Dockerfile.django
    container_name: calendar_django
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - RUN_ENV=docker
      - DB_HOST_DOCKER=db
      - DB_HOST_LOCAL=localhost
    ports:
      - "8000:8000"
    volumes:
      - ./django-admin-panel:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: calendar_bot
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  postgres_data: