# Generated by Django 5.2.10 on 2026-02-27 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BotStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("user_count", models.PositiveIntegerField(default=0)),
                ("event_count", models.PositiveIntegerField(default=0)),
                ("edited_events", models.PositiveIntegerField(default=0)),
                ("cancelled_events", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Статистика бота",
                "verbose_name_plural": "Статистика бота",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "telegram_id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Пользователь бота",
                "verbose_name_plural": "Пользователи бота",
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="UserStatistics",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="statistics",
                        serialize=False,
                        to="events.userprofile",
                    ),
                ),
                ("created_events", models.PositiveIntegerField(default=0)),
                ("edited_events", models.PositiveIntegerField(default=0)),
                ("cancelled_events", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Личная статистика пользователя",
                "verbose_name_plural": "Личная статистика пользователей",
                "db_table": "user_statistics",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("event_date", models.DateField()),
                ("event_time", models.TimeField()),
                ("details", models.TextField(blank=True, default="")),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Публичное событие"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="events.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "events",
                "ordering": ["-event_date", "-event_time"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("participant_telegram_id", models.BigIntegerField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("details", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("confirmed", "Подтверждено"),
                            ("declined", "Отклонено"),
                            ("cancelled", "Отменено"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Встреча",
                "verbose_name_plural": "Встречи",
                "db_table": "appointments",
                "unique_together": {("event", "participant_telegram_id")},
            },
        ),
    ]
