# Generated by Django 5.2.10 on 2026-02-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "db_table": "users",
                "managed": True,
                "verbose_name": "Пользователь бота",
                "verbose_name_plural": "Пользователи бота",
            },
        ),
    ]
