# Generated by Django 6.0.2 on 2026-02-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_auto_20260227_1319"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "Пользователь бота",
                "verbose_name_plural": "Пользователи бота",
            },
        ),
    ]
