# Generated by Django 6.0.2 on 2026-02-27 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_userprofile_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userstatistics",
            name="user",
        ),
        migrations.AddField(
            model_name="userstatistics",
            name="user_telegram_id",
            field=models.OneToOneField(
                db_column="user_telegram_id",
                default=289988039,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="statistics",
                serialize=False,
                to="events.userprofile",
            ),
            preserve_default=False,
        ),
    ]
