# Generated by Django 5.2.10 on 2026-03-03 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_add_export_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Встреча",
                "verbose_name_plural": "Встречи",
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["-event_date", "-event_time"],
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "ordering": ["-registered_at"],
                "verbose_name": "Пользователь бота",
                "verbose_name_plural": "Пользователи бота",
            },
        ),
        migrations.AlterModelOptions(
            name="userstatistics",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Личная статистика пользователя",
                "verbose_name_plural": "Личная статистика пользователей",
            },
        ),
        migrations.AlterField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateField(verbose_name="Дата встречи"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="details",
            field=models.TextField(
                blank=True, default="", verbose_name="Детали встречи"
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="events.event",
                verbose_name="Событие",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organized_appointments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Организатор",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="participant_telegram_id",
            field=models.BigIntegerField(verbose_name="Telegram ID участника"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает подтверждения"),
                    ("confirmed", "Подтверждено"),
                    ("declined", "Отклонено"),
                    ("cancelled", "Отменено"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="time",
            field=models.TimeField(verbose_name="Время встречи"),
        ),
        migrations.AlterField(
            model_name="botstatistics",
            name="cancelled_events",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Отменено событий"
            ),
        ),
        migrations.AlterField(
            model_name="botstatistics",
            name="date",
            field=models.DateField(unique=True, verbose_name="Дата статистики"),
        ),
        migrations.AlterField(
            model_name="botstatistics",
            name="edited_events",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Отредактировано событий"
            ),
        ),
        migrations.AlterField(
            model_name="botstatistics",
            name="event_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Создано событий"
            ),
        ),
        migrations.AlterField(
            model_name="botstatistics",
            name="user_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество пользователей"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="details",
            field=models.TextField(
                blank=True, default="", verbose_name="Детали события"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_date",
            field=models.DateField(verbose_name="Дата события"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_time",
            field=models.TimeField(verbose_name="Время события"),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название события"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="export_token",
            field=models.CharField(
                blank=True,
                help_text="Секретный токен для безопасной выгрузки",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Токен выгрузки",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Фамилия"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="registered_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата регистрации"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="telegram_id",
            field=models.BigIntegerField(
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Telegram ID",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="username",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Имя пользователя"
            ),
        ),
        migrations.AlterField(
            model_name="userstatistics",
            name="cancelled_events",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Отменено событий"
            ),
        ),
        migrations.AlterField(
            model_name="userstatistics",
            name="created_events",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Создано событий"
            ),
        ),
        migrations.AlterField(
            model_name="userstatistics",
            name="edited_events",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Отредактировано событий"
            ),
        ),
        migrations.AlterField(
            model_name="userstatistics",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="userstatistics",
            name="user_telegram_id",
            field=models.OneToOneField(
                db_column="user_telegram_id",
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="statistics",
                serialize=False,
                to="events.userprofile",
                verbose_name="Пользователь",
            ),
        ),
    ]
