# Generated by Django 6.0.5 on 2026-05-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_appointment_options_alter_event_options_and_more'),
    ]

    operations = [
        # Переименовываем таблицу users в events_userprofile
        migrations.RunSQL(
            "ALTER TABLE users RENAME TO events_userprofile;",
            "ALTER TABLE events_userprofile RENAME TO users;"
        ),
        # Обновляем имя таблицы в Django ORM
        migrations.RunSQL(
            "UPDATE django_content_type SET model='userprofile' WHERE app_label='events' AND model='userprofile';"
        ),
    ]
